/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout/route'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as PathlessLayoutIndexImport } from './routes/_pathlessLayout/index'
import { Route as PathlessLayoutSignupIndexImport } from './routes/_pathlessLayout/signup/index'
import { Route as PathlessLayoutPricingIndexImport } from './routes/_pathlessLayout/pricing/index'
import { Route as PathlessLayoutLoginIndexImport } from './routes/_pathlessLayout/login/index'
import { Route as PathlessLayoutFeaturesIndexImport } from './routes/_pathlessLayout/features/index'
import { Route as PathlessLayoutContactIndexImport } from './routes/_pathlessLayout/contact/index'
import { Route as PathlessLayoutAboutIndexImport } from './routes/_pathlessLayout/about/index'

// Create/Update Routes

const PathlessLayoutRouteRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const PathlessLayoutIndexRoute = PathlessLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)

const PathlessLayoutSignupIndexRoute = PathlessLayoutSignupIndexImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)

const PathlessLayoutPricingIndexRoute = PathlessLayoutPricingIndexImport.update(
  {
    id: '/pricing/',
    path: '/pricing/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any,
)

const PathlessLayoutLoginIndexRoute = PathlessLayoutLoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)

const PathlessLayoutFeaturesIndexRoute =
  PathlessLayoutFeaturesIndexImport.update({
    id: '/features/',
    path: '/features/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)

const PathlessLayoutContactIndexRoute = PathlessLayoutContactIndexImport.update(
  {
    id: '/contact/',
    path: '/contact/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any,
)

const PathlessLayoutAboutIndexRoute = PathlessLayoutAboutIndexImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/_pathlessLayout/': {
      id: '/_pathlessLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutIndexImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/_pathlessLayout/about/': {
      id: '/_pathlessLayout/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PathlessLayoutAboutIndexImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/contact/': {
      id: '/_pathlessLayout/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PathlessLayoutContactIndexImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/features/': {
      id: '/_pathlessLayout/features/'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof PathlessLayoutFeaturesIndexImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/login/': {
      id: '/_pathlessLayout/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PathlessLayoutLoginIndexImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/pricing/': {
      id: '/_pathlessLayout/pricing/'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PathlessLayoutPricingIndexImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/signup/': {
      id: '/_pathlessLayout/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PathlessLayoutSignupIndexImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
  }
}

// Create and export the route tree

interface PathlessLayoutRouteRouteChildren {
  PathlessLayoutIndexRoute: typeof PathlessLayoutIndexRoute
  PathlessLayoutAboutIndexRoute: typeof PathlessLayoutAboutIndexRoute
  PathlessLayoutContactIndexRoute: typeof PathlessLayoutContactIndexRoute
  PathlessLayoutFeaturesIndexRoute: typeof PathlessLayoutFeaturesIndexRoute
  PathlessLayoutLoginIndexRoute: typeof PathlessLayoutLoginIndexRoute
  PathlessLayoutPricingIndexRoute: typeof PathlessLayoutPricingIndexRoute
  PathlessLayoutSignupIndexRoute: typeof PathlessLayoutSignupIndexRoute
}

const PathlessLayoutRouteRouteChildren: PathlessLayoutRouteRouteChildren = {
  PathlessLayoutIndexRoute: PathlessLayoutIndexRoute,
  PathlessLayoutAboutIndexRoute: PathlessLayoutAboutIndexRoute,
  PathlessLayoutContactIndexRoute: PathlessLayoutContactIndexRoute,
  PathlessLayoutFeaturesIndexRoute: PathlessLayoutFeaturesIndexRoute,
  PathlessLayoutLoginIndexRoute: PathlessLayoutLoginIndexRoute,
  PathlessLayoutPricingIndexRoute: PathlessLayoutPricingIndexRoute,
  PathlessLayoutSignupIndexRoute: PathlessLayoutSignupIndexRoute,
}

const PathlessLayoutRouteRouteWithChildren =
  PathlessLayoutRouteRoute._addFileChildren(PathlessLayoutRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof PathlessLayoutRouteRouteWithChildren
  '/': typeof PathlessLayoutIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/about': typeof PathlessLayoutAboutIndexRoute
  '/contact': typeof PathlessLayoutContactIndexRoute
  '/features': typeof PathlessLayoutFeaturesIndexRoute
  '/login': typeof PathlessLayoutLoginIndexRoute
  '/pricing': typeof PathlessLayoutPricingIndexRoute
  '/signup': typeof PathlessLayoutSignupIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof PathlessLayoutIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/about': typeof PathlessLayoutAboutIndexRoute
  '/contact': typeof PathlessLayoutContactIndexRoute
  '/features': typeof PathlessLayoutFeaturesIndexRoute
  '/login': typeof PathlessLayoutLoginIndexRoute
  '/pricing': typeof PathlessLayoutPricingIndexRoute
  '/signup': typeof PathlessLayoutSignupIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteRouteWithChildren
  '/_pathlessLayout/': typeof PathlessLayoutIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_pathlessLayout/about/': typeof PathlessLayoutAboutIndexRoute
  '/_pathlessLayout/contact/': typeof PathlessLayoutContactIndexRoute
  '/_pathlessLayout/features/': typeof PathlessLayoutFeaturesIndexRoute
  '/_pathlessLayout/login/': typeof PathlessLayoutLoginIndexRoute
  '/_pathlessLayout/pricing/': typeof PathlessLayoutPricingIndexRoute
  '/_pathlessLayout/signup/': typeof PathlessLayoutSignupIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/'
    | '/dashboard'
    | '/about'
    | '/contact'
    | '/features'
    | '/login'
    | '/pricing'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/about'
    | '/contact'
    | '/features'
    | '/login'
    | '/pricing'
    | '/signup'
  id:
    | '__root__'
    | '/_pathlessLayout'
    | '/_pathlessLayout/'
    | '/dashboard/'
    | '/_pathlessLayout/about/'
    | '/_pathlessLayout/contact/'
    | '/_pathlessLayout/features/'
    | '/_pathlessLayout/login/'
    | '/_pathlessLayout/pricing/'
    | '/_pathlessLayout/signup/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PathlessLayoutRouteRoute: typeof PathlessLayoutRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  PathlessLayoutRouteRoute: PathlessLayoutRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_pathlessLayout",
        "/dashboard/"
      ]
    },
    "/_pathlessLayout": {
      "filePath": "_pathlessLayout/route.tsx",
      "children": [
        "/_pathlessLayout/",
        "/_pathlessLayout/about/",
        "/_pathlessLayout/contact/",
        "/_pathlessLayout/features/",
        "/_pathlessLayout/login/",
        "/_pathlessLayout/pricing/",
        "/_pathlessLayout/signup/"
      ]
    },
    "/_pathlessLayout/": {
      "filePath": "_pathlessLayout/index.tsx",
      "parent": "/_pathlessLayout"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/_pathlessLayout/about/": {
      "filePath": "_pathlessLayout/about/index.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/contact/": {
      "filePath": "_pathlessLayout/contact/index.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/features/": {
      "filePath": "_pathlessLayout/features/index.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/login/": {
      "filePath": "_pathlessLayout/login/index.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/pricing/": {
      "filePath": "_pathlessLayout/pricing/index.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/signup/": {
      "filePath": "_pathlessLayout/signup/index.tsx",
      "parent": "/_pathlessLayout"
    }
  }
}
ROUTE_MANIFEST_END */
